### ISSUE TITLE
Incorrect example code under `docs/events` page

### ISSUE THREAD

**Issue by HighnessAtharva** [pynecone-io/pcweb#2]
Refer - [Events Docs Page](https://pynecone.io/docs/state/events)

Incorrect code example under the heading of `Event Chains`

`def index():` -> function code is incorrect. State class code is correct. Please fix it. 

**Possible FIX:** I think the typo in source code should be fixed from code(14) to code(4). Still, not entirely sure.

**Comment by picklelo** [comment]
Yup good catch! Just pushed a fix. We're redeploying the site today.
