### ISSUE TITLE
[Server Error]TypeError: arg_state.colors.at is not a function

### ISSUE THREAD

**Issue by 123385918** [pynecone-io/pcweb#58]
the code in https://pynecone.io/docs/state/vars does not work.
```python
class ArgState(pc.State):
    colors: list[str] = [
        "rgba(222,44,12)",
        "white",
        "#007ac2",
    ]

    def change_color(self, color, index):
        self.colors[index] = color


def index():
    return pc.hstack(
        pc.input(
            default_value=ArgState.colors[0],
            on_blur=lambda c: ArgState.change_color(c, 0),
            bg=ArgState.colors[0],
        ),
        pc.input(
            default_value=ArgState.colors[1],
            on_blur=lambda c: ArgState.change_color(c, 1),
            bg=ArgState.colors[1],
        ),
        pc.input(
            default_value=ArgState.colors[2],
            on_blur=lambda c: ArgState.change_color(c, 2),
            bg=ArgState.colors[2],
        ),
    )
```
error msg:
> Server Error
> TypeError: arg_state.colors.at is not a function
> This error happened while generating the page. Any console logs will be displayed in the terminal window.

**Comment by ElijahAhianyo** [comment]
This works just fine for me, What Pynecone version do you use?

**Comment by 123385918** [comment]
> This works just fine for me, What Pynecone version do you use?
this is ```pip show pynecone``` result:
Name: pynecone
Version: 0.1.24

**Comment by ElijahAhianyo** [comment]
> > This works just fine for me, What Pynecone version do you use?
> > this is `pip show pynecone` result:
> > Name: pynecone
> > Version: 0.1.24

can you post your full console logs of the errors as well as the full code you're currently running?

**Comment by 123385918** [comment]
> > > This works just fine for me, What Pynecone version do you use?
> > > this is `pip show pynecone` result:
> > > Name: pynecone
> > > Version: 0.1.24
> 
> can you post your full console logs of the errors as well as the full code you're currently running?

Here it is. Thanks so much.
```
import {useEffect, useRef, useState} from "react"

import {useRouter} from "next/router"

import {E, connect, updateState, uploadFiles} from "/utils/state"

import "focus-visible/dist/focus-visible"

import {HStack, Input, useColorMode} from "@chakra-ui/react"

import NextHead from "next/head"



const PING = "http://localhost:8000/ping"

const EVENT = "ws://localhost:8000/event"

const UPLOAD = "http://localhost:8000/upload"

export default function Component() {

const [arg_state, setArg_state] = useState({"colors": ["rgba(222,44,12)", "white", "#007ac2"], "pick_color": "rgba(222,44,12)", "events": [{"name": "arg_state.hydrate"}], "files": []})

const [result, setResult] = useState({"state": null, "events": [], "processing": false})

const router = useRouter()

const socket = useRef(null)

const { isReady } = router;

const { colorMode, toggleColorMode } = useColorMode()

const Event = events => setArg_state({

  ...arg_state,

  events: [...arg_state.events, ...events],

})

const File = files => setArg_state({

  ...arg_state,

  files,

})

useEffect(() => {

  if(!isReady) {

    return;

  }

  if (!socket.current) {

    connect(socket, arg_state, setArg_state, result, setResult, router, EVENT, ['websocket', 'polling'])

  }

  const update = async () => {

    if (result.state != null) {

      setArg_state({

        ...result.state,

        events: [...arg_state.events, ...result.events],

      })

      setResult({

        state: null,

        events: [],

        processing: false,

      })

    }

    await updateState(arg_state, setArg_state, result, setResult, router, socket.current)

  }

  update()

})

return (

<HStack><Input defaultValue={arg_state.colors.at(0)}

onBlur={(_e) => Event([E("arg_state.change_color", {color:_e.target.value,index:0})])}

sx={{"bg": arg_state.colors.at(0)}}

type="text"/>

<Input defaultValue="red"

onBlur={(_e) => Event([E("arg_state.change_color", {color:_e.target.value,index:0})])}

sx={{"bg": "red"}}

type="text"/>

<NextHead><title>{`Pynecone App`}</title>

<meta content="A Pynecone app."

name="description"/>

<meta content="favicon.ico"

property="og:image"/></NextHead></HStack>

)

}
```

**Comment by ElijahAhianyo** [comment]
> > > > This works just fine for me, What Pynecone version do you use?
> > > > this is `pip show pynecone` result:
> > > > Name: pynecone
> > > > Version: 0.1.24
> > 
> > can you post your full console logs of the errors as well as the full code you're currently running?
> 
> Here it is. Thanks so much.
> ```
> import {useEffect, useRef, useState} from "react"
> 
> import {useRouter} from "next/router"
> 
> import {E, connect, updateState, uploadFiles} from "/utils/state"
> 
> import "focus-visible/dist/focus-visible"
> 
> import {HStack, Input, useColorMode} from "@chakra-ui/react"
> 
> import NextHead from "next/head"
> 
> 
> 
> const PING = "http://localhost:8000/ping"
> 
> const EVENT = "ws://localhost:8000/event"
> 
> const UPLOAD = "http://localhost:8000/upload"
> 
> export default function Component() {
> 
> const [arg_state, setArg_state] = useState({"colors": ["rgba(222,44,12)", "white", "#007ac2"], "pick_color": "rgba(222,44,12)", "events": [{"name": "arg_state.hydrate"}], "files": []})
> 
> const [result, setResult] = useState({"state": null, "events": [], "processing": false})
> 
> const router = useRouter()
> 
> const socket = useRef(null)
> 
> const { isReady } = router;
> 
> const { colorMode, toggleColorMode } = useColorMode()
> 
> const Event = events => setArg_state({
> 
>   ...arg_state,
> 
>   events: [...arg_state.events, ...events],
> 
> })
> 
> const File = files => setArg_state({
> 
>   ...arg_state,
> 
>   files,
> 
> })
> 
> useEffect(() => {
> 
>   if(!isReady) {
> 
>     return;
> 
>   }
> 
>   if (!socket.current) {
> 
>     connect(socket, arg_state, setArg_state, result, setResult, router, EVENT, ['websocket', 'polling'])
> 
>   }
> 
>   const update = async () => {
> 
>     if (result.state != null) {
> 
>       setArg_state({
> 
>         ...result.state,
> 
>         events: [...arg_state.events, ...result.events],
> 
>       })
> 
>       setResult({
> 
>         state: null,
> 
>         events: [],
> 
>         processing: false,
> 
>       })
> 
>     }
> 
>     await updateState(arg_state, setArg_state, result, setResult, router, socket.current)
> 
>   }
> 
>   update()
> 
> })
> 
> return (
> 
> <HStack><Input defaultValue={arg_state.colors.at(0)}
> 
> onBlur={(_e) => Event([E("arg_state.change_color", {color:_e.target.value,index:0})])}
> 
> sx={{"bg": arg_state.colors.at(0)}}
> 
> type="text"/>
> 
> <Input defaultValue="red"
> 
> onBlur={(_e) => Event([E("arg_state.change_color", {color:_e.target.value,index:0})])}
> 
> sx={{"bg": "red"}}
> 
> type="text"/>
> 
> <NextHead><title>{`Pynecone App`}</title>
> 
> <meta content="A Pynecone app."
> 
> name="description"/>
> 
> <meta content="favicon.ico"
> 
> property="og:image"/></NextHead></HStack>
> 
> )
> 
> }
> ```

Actually, I'm more interested in your python file than the generated js file. But from your js file, I can already see an issue with your input default_value referencing an unknown field `arg_state.colors.at`. It would be helpful if you shared your python file

**Comment by 123385918** [comment]
OK, I know.
```python
import pynecone as pc

class State(pc.State):
    colors: list[str] = [
        "rgba(222,44,12)",
        "white",
        "#007ac2",
    ]

    def change_color(self, color, index):
        self.colors[index] = color


def index():
    return pc.hstack(
        pc.input(
            default_value=State.colors[0],
            on_blur=lambda c: State.change_color(c, 0),
            bg=State.colors[0],
        ),
        pc.input(
            default_value=State.colors[1],
            on_blur=lambda c: State.change_color(c, 1),
            bg=State.colors[1],
        ),
        pc.input(
            default_value=State.colors[2],
            on_blur=lambda c: State.change_color(c, 2),
            bg=State.colors[2],
        ),
    )

app = pc.App(state=State)
app.add_page(index)
app.compile()
```
Here is the my.py code .

**Comment by ElijahAhianyo** [comment]
@123385918  That's interesting, I just tried out this exact code and it works. What's your node version?

**Comment by 123385918** [comment]
I just update my Node.js  to current(20.0.0) and it works well.
